### ISSUE TITLE
Update Electrum (1.9.8 is discontinued)

### ISSUE THREAD

**Issue by wzrdtales** [bitkey/bitkey#13]
Electrum 1.9.8 is discontinued and most of the available remote servers do not accept any queries from it anymore. 
This renders bitkey useless, before I start on a PR instead of building a complete new thing I wanted to ask: Is this project still maintained? Seems to be pretty dead though, waiting 1 week from now and then I am going to mark this as dead.

thank you

**Comment by JedMeister** [comment]
BitKey is not abandoned per se, just not getting anywhere near the love that it deserves... It was a bit of a side project for Alon (@alonswartz)  & Liraz (@lirazsiri) (the co-founders of [TurnKey Linux](https://www.turnkeylinux.org/)) and after it's initial release, they haven't had much time to get back to it. 

It really needs at least a basic update to Debian Jessie base so that it will build successfully. At least then interested users (such as yourself) can tweak other components as need be.

I will suggest that they consider at least updating it enough so that it builds when they get a chance...

**Comment by lirazsiri** [comment]
This has been fixed and a new version will be pushed out soon.
