### ISSUE TITLE
bitkey-data/cold-offline is highly compressible; should not be

### ISSUE THREAD

**Issue by scottj97** [bitkey/bitkey#32]
My Electrum wallet is stored on a USB key with filename bitkey-data/cold-offline. This is an encrypted volume of approximately 5MB.

A proper encrypted volume should be (more or less) indistinguishable from totally random data and therefore incompressible. But zip can compress this cold-offline file by approximately 94%.

Isn't this bad? Doesn't this make it easier for an attacker to decrypt the volume?

**Comment by lirazsiri** [comment]
Hi Scott. Good question!

 No, it doesn't make it any easier to decrypt your wallet. It's just a tiny bit inefficient because we created a bigger loopback filesystem than we  need and zeroed it out with dd, which is why it compresses so well. If we had initialized that file with /dev/urandom it wouldn't compress at all, but you wouldn't get any better security for this use case. Being compressible is a feature. 

Regarding encryption, all blocks written to the cold-offline filesystem are encrypted and the cryptographic strength of each block is independent of any other blocks.

You can tell how many encrypted blocks are written to the filesystem, which you would know anyway because we don't randomize the file names and cold-offline is a pretty big giveaway that you're using bitkey. If we randomized the file names of the wallet it would make it kind of difficult to figure out for BitKey to figure out which file to open for your cold wallet. Bottom line, it's not a secret.

You can take a look at how the encrypted volume is implemented in /usr/local/bin/electrum-wrapper. Standard linux tools are used for everything.

Sorry for the late response! Jeremy just gave me a kick in the pants that I hadn't noticed this.
