### ISSUE TITLE
Support 32bit arch

### ISSUE THREAD

**Issue by cisba** [bitkey/bitkey#40]
An old notebook is a perfect cold storage.
Is there any reason to not publish also a 32bit iso?

**Comment by lirazsiri** [comment]
You just have to rebuild everything. More work. These days even old
notebooks support 64-bit. But I guess that depends on your definition of
old. It would be nice to have more architectures supported including arm in
the Raspberry Pi.

On Jun 24, 2017 6:31 PM, "Emanuele Cisbani" <notifications@github.com>
wrote:

An old notebook is a perfect cold storage.
Is there any reason to not publish also a 32bit iso?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitkey/bitkey/issues/40>, or mute the thread

**Comment by tuberculo** [comment]
I have two 32-bit netbooks, so a 32-bit build would be great for me.

**Comment by tuberculo** [comment]
Hi, @JedMeister 
Is it possible to build a 32bit version? Is it something simple to do?

**Comment by JedMeister** [comment]
Sorry for slow response @tuberculo. In theory it should be as simple as downloading the 32 bit TKLDev (it's on our mirror here: http://mirror.turnkeylinux.org/turnkeylinux/images/iso/turnkey-tkldev-14.1-jessie-i386.iso) and running through the usual steps. Note though, that that is v14.1. We didn't do a v14.2 32 bit release at all. It's unlikely that we will ever be doing "official" 32 bit builds in the future. AFAIK, no one has been building x86 32 bit hardware for quite a few years now. We'll likely consider ARM builds in the future though.

Having said that, I'm not sure if all the software is available in 32 bit. If there are 32 bit packages missing, then you may be able to build them yourself. Again in theory, whilst a bit of a pain, that should be possible. However, I suspect that will be a real pain! Whilst the [TKLDev docs](https://github.com/turnkeylinux-apps/tkldev/tree/master/docs) cover [building packages from source](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/advanced/building-packages-from-source.rst), the pre-setup was only included in v14.2. I'm fairly sure that it will involve some fiddling to get it all set up. 

Once you have it set up though, then you should be able to use that same TKLDev to build future releases as well. At least until v15.x (the next major release) reaches EOL...!

If you want to have a go, then please do so. I'll try to help you as much as i can, but I'm pretty busy ATM and heading off for a week very soon, so I'm not sure how useful I'll be to you.

Good luck!

**Comment by JedMeister** [comment]
Hi guys, sorry about this, but as BitKey is based on TurnKey Linux and we've deprecated 32 bit, there is no anticipation of ongoing 32 bit support for BitKey. Sorry about that, but it's just not feasible (from a resource perspective) for us to maintain 32 bit support. :cry:
