### ISSUE TITLE
QRCode for transactions instead of USB

### ISSUE THREAD

**Issue by estevaocm** [bitkey/bitkey#48]
Hello, big fan here. I realize this project is for your own convenience, but would it be possible for the next release to enable loading transactions from QRCodes in Electrum by using the camera? I don't suppose this would be a security breach in itself. Are camera drivers a problem? I suppose basic drivers could suffice?

I have not yet entered BitCoin exchange, still studying the technologies involved, but I am thinking I might use BitKey for my cold offline wallet, while preparing and broadcasting my transactions in my usual, potentially compromised PC. For this scenario, I figure it would be safest and fastest to generate a QRCode for the transaction, then load it into Electrum in the cold offline system; the signed transaction could then be broadcasted or sent to my PC from my mobile phone.

Security-wise, am I missing something here? What do you think of this use case?

**Comment by estevaocm** [comment]
Of course, BitKey already enables creating QRCodes, so at least the signed transaction gets to be read optically and then broadcasted without tampering. But malware can still get in the system by USB, even if it can't get out.

I'm actually putting an effort towards updating BitKey's source with Electrum 3.0.2 and zbar, but it has been a struggle. At present I can't get easy_install to work, after switching python with python3. Didn't expect this much trouble, will need more time to actually get somewhere.

**Comment by JedMeister** [comment]
Hey there. Sorry for the lack of feedback and input. BitKey is a side project for us and personally, I'm not familiar with it (I'm not on the bitcoin bandwagon; I was always planning to, but figured I've left my run way too late now...). 

Having said that, I'm well versed in Debian and TurnKey in general (including our TKLDev build tool), so may be able to be of some assistance...

Regarding your issue with easy_install on Python3, have you installed the Python3 version of easy_install? If not, that would certainly explain your issues! :wink: 

Try this:
```
sudo apt-get update && sudo apt-get install python3-setuptools
```

Obviously that is only for testing, to include it in your build, add the package to the plan (`plan/main`).

**Comment by estevaocm** [comment]
Hi Jeremy! Yes, I did install that package, which is why I am confused. I also find it odd that I've removed the old python but 2.7 still gets installed, probably as a dependency for something else.

I'm still new to Turnkey and Bitkey, so I'm only working on the plan, don't yet know how to test it first and use apt-get, since the final output would be an ISO but it fails.

**Comment by JedMeister** [comment]
> Hi Jeremy! Yes, I did install that package, which is why I am confused. I also find it odd that I've removed the old python but 2.7 still gets installed, probably as a dependency for something else

As python2.x is default python in Debian Jessie (what the current build is based on - actually it's still the default python in Stretch) there will be lots of things that depend on it. Are you calling the python3 version of easy_install explicitly? I.e.:
```
easy_install3 ...
```
Or the internet suggest that alternatively, you can launch it via python (untested):
```
python3 -m easy_install ...
```

> I'm still new to Turnkey and Bitkey, so I'm only working on the plan, don't yet know how to test it first and use apt-get, since the final output would be an ISO but it fails.

TKLDev is designed for building all of our headless server appliances. Whilst it also works great for building BitKey, it doesn't currently support easy/proper testing during the build (as you can with a headless server). 

However, rather than having to rebuild from scratch each time, you can play in the sandbox (i.e. `fab-chroot build/root.sandbox`) and use apt and other commandline tools to install or tweak software to be included in the ISO (`exit` when you're done).

Then to rebuild the ISO to include the sandbox changes, you should skip running `make clean` (that deletes everything and starts again from scratch) and just run `make` again. TKLDev should see that the sandbox is dirty and include it in the ISO. It's been a little while since I used that functionality, but hopefully it's all still working as it should...

TBH, I'm not sure how much better it will be because you'll still need to rebuild the ISO each time to test properly, but hopefully it speeds things up a bit. 

If you want specific assistance with build issues you're having, please feel free to post on our [forums](https://www.turnkeylinux.org/forum)

**Comment by estevaocm** [comment]
Thanks, Jeremy. I couldn't actually speed things up until I was actually able to build the ISO. I've removed the Electrum 3 dependencies from my conf.d/electrum and added them to plan/apps and it worked (python3-setuptools, python3-pyqt5, python-jsonrpclib, python-qrcode, python-slowaes, python-protobuf, python3-ecdsa, python3-requests, python3-six, python3-colorama, python3-dnspython). I also threw in python-zbar to see if I could get the QR Code reading to work in Electrum, but it just crashes. Also it seems to not be freeing resources because if I close Electrum and reopen it fails saying the USB drive is already in use and suggests to unmount (tested this even without the aformentioned crash).

So my updated image is probably good enough for signing from a USB drive but is not very stable and still unable to read QR Code. I suppose drivers are missing or something.

**Comment by estevaocm** [comment]
I've noticed electrum-wrapper calls electrum deseed, which was removed in Electrum 3. Maybe this is causing the USB block issue. Will investigate further...

**Comment by estevaocm** [comment]
To confirm, I had to comment the lines that create the online wallet with deseed, a command which is no longer provided, so the unmount can proceed successfully:

`# create seedless watch wallet (cold-online)`
`#if [ -e "$wallet_path" ] && [ ! -e "$storage_path/cold-online" ]; then`
`    #info "creating $storage_path/cold-online..."`
`    #echo y | electrum deseed -w $wallet_path`
`    #mv $wallet_path.seedless $storage_path/cold-online`
`#fi`

When I try to load a transaction by QR Code I get a segmentation fault at line 130:

`electrum $extra_args --wallet=$wallet_path`

I have verified that $extra_args==--offline && $wallet_path==/mnt/bitkey-data/cold-offline as expected, and no details are given, so there must be another error hidden in the stack.

**Comment by estevaocm** [comment]
I have tried an offline web QR scanner from my USB drive and the browser console indicates that there is no access to the camera. This may be the cause of Electrum's segmentation fault, though my expectation was for it to fail gracefully. Anyhow, I could solve this with a web QR scanner but must find out how to enable the camera first.

**Comment by estevaocm** [comment]
Okay, I included the package "cheese" in my build and this has enabled my USB webcam in my ISO running on a virtual machine. I generated the QR for a transaction preview in my host system running a watch only wallet and successfully scanned the QR to the guest Bitkey system.

I'll share the code for this soon, but the process can be replicated by following my comments in this thread.

Cheers!

**Comment by estevaocm** [comment]
I have forked into https://github.com/estevaocm/bitkey/
Changes:
- Electrum upgraded to 3.0.2
- Electrum dependencies upgraded by the TKLDev plan (maybe less secure, but was more convenient for me), including Python3
- cheese and zbar included for webcam QRCode scan support
- Web QRCode scanner located at /home/user/webqr

**Comment by JedMeister** [comment]
Great work @estevaocm! Sounds like you are having some great progress! Thanks for posting notes.

**Comment by estevaocm** [comment]
Thanks, @JedMeister. It was a lot of work but pretty rewarding.

I'd say the TODO list for my fork would be to repackage Electrum's dependencies with their hashes as in the main branch for added security and find a way to export the cold-online-wallet which was disabled by upgrading Electrum to 3, which has ended the deseed function. Although in my opinion the other boot modes are no longer necessary as you can use just your mobile device and the cold-offline-wallet mode to operate securely. I'd probably even remove the other options.

**Comment by estevaocm** [comment]
BTW, @JedMeister, I wonder how secure are TKLDev's package download routines. Specifically, if the downloads are encrypted and if the hashes are verified. I bring this up because I saw that the other Bitkey devs bothered to put all Electrum's dependencies in overlay with their respective hashes, as if they did not trust the package downloads in TKLDev. Or maybe its simply for auditing? For myself, I figure TKLDev is secure enough, especially as I burn the system to a CD, which can not be (further) tampered with, and only use offline mode and no USB drive other than the wallet, so no information should escape from the system anyway.

**Comment by JedMeister** [comment]
Re the issue of security, we include the code and the hashes (rather than downloading on the fly during build) is primarily to reduce the trust requirement. 

Firstly, pip/PyPI has some significant and very real security issues. Theoretically, anyone could upload something malicious there and everybody installing or updating via `pip` would be affected (possibly infected, depending on what malicious code was injected). Numerous other language specific package managers have the same or similar issues (I'm thinking of [npm](https://ponyfoo.com/articles/npm-meltdown-security-concerns) as a relatively recent real world scenario). Obviously pip/PyPI works differently and wouldn't succumb to that particular npm issue, but it does still require you to trust PyPI (and the developers uploading and/or the code hosted there). 

Obviously the code can change at any time. So providing the particular dependencies within the overlay, rather than downloading the latest version, means that we don't need to trust that the latest version is ok. Prior to "official" rebuild and release of BitKey, we do a brief code review on the modules that are included. Obviously we wouldn't be able to do that if they were downloaded on the fly. 

In a use case such as BitKey, we want to rely on as little trust as possible (users trusting us and us trusting PyPI). The value of including the code (code review of know version) was discussed above and essentially means that we don't need to trust PyPI. Including the hash makes it easy for end users to confirm that we are actually including the same version of dependencies as are provided via PyPI (i.e. user don't need to trust us that the code is complete and hasn't been tampered with).

Regarding your other comments, they sound pretty fair and valid, but as I'm not a user, I can't really comment. Thanks again for sharing all of this though! As you've probably seen, I've directed a few others to this thread. Hopefully they may chime in and assist you with testing and development. :smile:

**Comment by estevaocm** [comment]
Thank you for your considerations, @JedMeister, you have been very helpful! I fully agree with your assessment.

Then I guess the Python sources should indeed be pre-downloaded to overlay and hashed for greater security. Maybe I or another collaborator could get to that with some free time.

**Comment by tuberculo** [comment]
Is this version working? @estevaocm do you need any help testing it?

**Comment by estevaocm** [comment]
Hi @tuberculo. The cold-offline mode is working. I have not tested the other modes (cold-online and hot-online).

Cold-online should not work because the deseed function was removed from Electrum and I have not yet found another way to generate a deseeded wallet (one with only the public key).

I have tested cold-offline mode with a simple Clone USB webcam and my notebook's Alcor Micro USB webcam. I generated a test wallet and also tested signing a transaction with my real wallet, which was already made by the official Bitkey. So I prepared the transaction with my mobile phone, generated the QR Code, loaded the transaction into Bitkey by scanning the QR with the webcam, signed in cold-offline mode, generated the QR for the signed transaction and scanned it back into the mobile phone. Everything went smoothly.

**Comment by tuberculo** [comment]
Great. I think I'll use your version, as there are some good new features in Electrum, like RBF and segwit. QR code scanning seems to be useful too.
 
I can see that you commented two lines in file Electrum-3.0.2/electrum. What is it for?

**Comment by estevaocm** [comment]
Yes, thank you for reminding me of that, that should be in my backlog. In the original Bitkey, that is deployed as a patch. Since I was in a hurry, I altered directly the source code. But I should try to make the patch work as in the master branch. As I understand it, that is for better compatibility with the Bitkey scheme of automatically storing and retrieving the wallet at a predefined location in the USB drive.

**Comment by estevaocm** [comment]
I have added issue https://github.com/estevaocm/bitkey/issues/5 to address this. To be honest, I don't yet know the tool that was used to create the patch files with line numbers, dates etc. so I could use some pointers for making the patch. Assuming it is actually necessary. Should be worthwhile to test the unpatched version first. I have little experience with Python but am experienced in Java so I know it's only a matter of taking the time to educate myself.

**Comment by estevaocm** [comment]
https://github.com/estevaocm/bitkey/releases/tag/14.2.0-qrscan-ether

**Comment by estevaocm** [comment]
New release now with Electrum-LTC and Electron-Cash working. (Must be manually executed from terminal from /usr/local/src)

https://github.com/estevaocm/bitkey/releases/tag/14.2.0-qrscan-altcoins

**Comment by estevaocm** [comment]
Latest release has only complete and unpatched source code packages for Electrum varieties, with the respective checksums and signatures.

In order to avoid having to manage dependencies, the packages are running directly from source, without installing with Python.

Added icons for Electrum-LTC, Electron Cash, My Ether Wallet and Web QR scanning (this one is currently failing with Chromium).

https://github.com/estevaocm/bitkey/releases/latest

**Comment by estevaocm** [comment]
My fork has been merged to the new community branch, so I'm closing this issue.
