### ISSUE TITLE
Why Chromium

### ISSUE THREAD

**Issue by UnoMamiko** [bitkey/bitkey#9]
And not Firefox? Or, better yet, the Tor Browser?

**Comment by firepol** [comment]
Hi, sorry to resuscitate this... but now Firefox released a new beast: Firefox Quantum. Would you consider adding Firefox Quantum? Or same arguments? Thanks and cheers.

**Comment by JedMeister** [comment]
I've read about the new Firefox Quantum and whilst it sounds cool, I'm yet to actually use it. As an aside, the new, improved Firefox sounds awesome, but I think the name sucks! It sounds like some BS marketing hype for some new pseudoscience gadget!

In the context of BitKey, the previous argument still stands. Not because there is anything fundamentally wrong with Firefox Quantum (it's probably as good, if not better than Chromium WRT security), just that it's not packaged for Debian stable yet (and won't be until the next stable release - in a year or 2).

So in the interests of security, we wouldn't look to include it as part of the default BitKey build. However, there would nothing stopping you from editing the buildcode to include it and rebuild your own custom BitKey version. I would recommend that you include a inithooks script to re-install on boot to make sure that it's up to date.

**Comment by firepol** [comment]
Ok, I forked the project already and I'll try to do as you said ;) about the re-install/update on boot, if you have some example on  how to do that (and some lines of code) that would be awesome. Thanks and cheers, Paolo

**Comment by JedMeister** [comment]
The first thing I'd do if I were you would be to try installing it on a running BitKey. If you do that via the commandline, then you can more-or-less copy paste that straight into a bash script (it needs to be non-interactive, if you get stuck, please post and I can help out). TBH, I'm not sure exactly what steps you'd need to take (and there are no doubt multiple ways for it to be done), so I can't really offer you any example code. But if you keep in mind that TurnKey v14.x (inc BitKey) are based on Debian Jessie (aka 'oldstable'). FWIW, we hope to update the base OS to Stretch by early next year (we've fallen behind a fair bit...).

Once you've got to a point where your script runs successfully on a fresh boot of BitKey, then you can add the script to the buildcode. Assuming that you want it to run on everyboot, in every BitKey mode, then my guess on the best spot to put it would be in `/usr/lib/inithooks/everyboot.d` (i.e. `overlay/usr/lib/inithooks/everyboot.d/firefox-install` in the buildcode). Make sure that it's executable (i.e. `chmod +x overlay/usr/lib/inithooks/everyboot.d/firefox-install`). I would also recommend that you make your script really verbose, so then you should be able to see what it's doing. Do that by setting `x` after the shebang. I.e. put this line at the very top of your script (very first line):
```
#!/bin/bash -e
```

I hope that helps. Let me know if you get stuck and I'll see what can do.
